config/routes.rb
Rails.application.routes.draw do
  root 'static_pages#top'
  get '/signup', to: 'users#new'

  # ログイン機能
  get    '/login', to: 'sessions#new'
  post   '/login', to: 'sessions#create'
  delete '/logout', to: 'sessions#destroy'
  
  # 拠点情報
  resources :bases
  
  resources :users do
    collection { post :import }
    member do
      get 'edit_basic_info'
      patch 'update_basic_info'
      # 1ヶ月の変更申請
      get 'attendances/edit_one_month'
      patch 'attendances/update_one_month' # この行が追加対象です。
      # 1ヶ月の勤怠申請
      patch 'attendances/update_manager_approval_request'
      # 勤怠の確認
      get 'show_confirmation'
      # 出勤社員一覧
      get 'list_of_commuting_employees'
    end
    
    resources :attendances, only: :update do
      member do
        # 残業申請
        get 'edit_overtime_request'
        patch 'update_overtime_request'
        # 残業承認
        get 'edit_overtime_notice'
        patch 'update_overtime_notice'
        # 勤怠承認
        get 'edit_attendance_change_notice'
        patch 'update_attendance_change_notice'
        # 所属長承認
        get 'edit_manager_approval_notice'
        patch 'update_manager_approval_notice'
        # 勤怠修正ログ
        get 'attendance_log'
      end
    end
  end
end

app/models/user.rb
class User < ApplicationRecord
  has_many :attendances, dependent: :destroy
  # 「remember_token」という仮想の属性を作成します。
  attr_accessor :remember_token
  before_save { self.email = email.downcase }

  validates :name, presence: true, length: { maximum: 50 }

  VALID_EMAIL_REGEX = /\A[\w+\-.]+@[a-z\d\-.]+\.[a-z]+\z/i
  validates :email, presence: true, length: { maximum: 100 },
                    format: { with: VALID_EMAIL_REGEX },
                    uniqueness: true
  # 所属の長さが2文字以上かつ50文字以下の検証を追加
  validates :affiliation, length: { in: 2..50 }, allow_blank: true
  # 社員番号が必ず存在させるために検証を追加
  validates :employee_number, presence: true, uniqueness: true
  # ユーザーIDが必ず存在させるために検証を追加
  validates :uid, presence: true, uniqueness: true
  # 基本勤務時間が必ず存在させるために検証を追加
  validates :basic_work_time, presence: true
  # 勤務時間が必ず存在させるために検証を追加
  validates :work_time, presence: true
  # 指定勤務開始時間が必ず存在させるために検証を追加
  validates :designated_work_start_time, presence: true
  # 指定勤務終了時間が必ず存在させるために検証を追加
  validates :designated_work_end_time, presence: true
  has_secure_password
  validates :password, presence: true, length: { minimum: 6 }, allow_nil: true

  # 渡された文字列のハッシュ値を返します。
  def User.digest(string)
    cost = 
      if ActiveModel::SecurePassword.min_cost
        BCrypt::Engine::MIN_COST
      else
        BCrypt::Engine.cost
      end
    BCrypt::Password.create(string, cost: cost)
  end

  # ランダムなトークンを返します。
  def User.new_token
    SecureRandom.urlsafe_base64
  end

  # 永続セッションのためハッシュ化したトークンをデータベースに記憶します。
  def remember
    self.remember_token = User.new_token
    update_attribute(:remember_digest, User.digest(remember_token))
  end

  # トークンがダイジェストと一致すればtrueを返します。
  def authenticated?(remember_token)
    # ダイジェストが存在しない場合はfalseを返して終了します。
    return false if remember_digest.nil?
    BCrypt::Password.new(remember_digest).is_password?(remember_token)
  end

  # ユーザーのログイン情報を破棄します。
  def forget
    update_attribute(:remember_digest, nil)
  end
  
  def self.import(file)
      CSV.foreach(file.path, headers: true) do |row|
      # IDが見つかれば、レコードを呼び出し、見つかれなければ、新しく作成
      user = find_by(id: row["id"]) || new
      # CSVからデータを取得し、設定する
      user.attributes = row.to_hash.slice(*updatable_attributes)
      user.save!(validate: false)
    end
  end
  
  # 更新を許可するカラムを定義
  def self.updatable_attributes
    ["name", "email", "affiliation", "employee_number", "uid",
      "basic_work_time", "designated_work_start_time", "designated_work_end_time",
      "superior", "admin", "password"]
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :set_user, only: [:show, :edit, :update, :destroy, :edit_basic_info, :update_basic_info, :show_confirmation, :list_of_commuting_employees]
  before_action :set_superior, only: [:show, :show_confirmation]
  before_action :logged_in_user, only: [:show, :index, :edit, :update, :destroy, :edit_basic_info, :update_basic_info]
  before_action :correct_user, only: [:edit, :update, :show]
  before_action :admin_user, only: [:index, :destroy, :edit_basic_info, :update_basic_info, :list_of_commuting_employees]
  before_action :set_one_month, only: [:show, :show_confirmation]
  before_action :not_admin, only: [:show]
  
  def index
    @users = User.paginate(page: params[:page])
  end

  # before_actionでまとめられないものがある。
  def show
    # @first_dayから@last_dayまでの範囲をworked_onの範囲として指定して、その範囲内の勤怠記録を検索
    # @first_dayと@last_dayはそれぞれ、選択された月の最初の日と最終の日を指すように設定する
    # @first_day = params[:date].nil? ? Date.today.beginning_of_month : Date.parse(params[:date])
    # @last_day = @first_day.end_of_month
    # @user.idを持つユーザーのAttendanceレコードをworked_onの日付が@first_dayから@last_dayの範囲内にあるものだけを検索
    # @attendances = Attendance.where(user_id: @user.id, worked_on: @first_day..@last_day)

    # idを指定すればid(1,2,3),nameを指定すれば名前を表示させる
    # @overtime_sum @user.id→@user.nameに変更
    # @attendances_sum @user.id→@user.nameに変更
    # @manager_sum @user.id→@user.nameに変更
    @worked_sum = @attendances.where.not(started_at: nil).count
    @overtime_sum = Attendance.where(overtime_request_superior: @user.name, overtime_request_status: "申請中").count
    @attendances_sum = Attendance.where(attendances_request_superior: @user.name, attendances_approval_status: "申請中").count
    @manager_sum = Attendance.where(manager_request_superior: @user.name, manager_request_status: "申請中").count
    # csv出力
    require 'csv'
    
    respond_to do |format|
      format.html
      format.csv do |csv|
        send_attendances_csv(@attendances)
      end
    end
  end
  
  def show_confirmation
    # @overtime_sum @user.id→@user.nameに変更
    # @attendances_sum @user.id→@user.nameに変更
    # @manager_sum @user.id→@user.nameに変更
    # @user.idを持つユーザーのAttendanceレコードをworked_onの日付が@first_dayから@last_dayの範囲内にあるものだけを検索
    @attendances = Attendance.where(user_id: @user.id, worked_on: @first_day..@last_day)
    @worked_sum = @attendances.where.not(started_at: nil).count
    @overtime_sum = Attendance.where(overtime_request_superior: @user.name, overtime_request_status: "申請中").count
    @attendances_sum = Attendance.where(attendances_request_superior: @user.name, attendances_approval_status: "申請中").count
    @manager_sum = Attendance.where(manager_request_superior: @user.name, manager_request_status: "申請中").count
  end
  
  def new
    @user = User.new
  end

  def create
    @user = User.new(user_params)
    if @user.save
      log_in @user
      flash[:success] = '新規作成に成功しました。'
      redirect_to @user
    else
      render :new
    end
  end

  def edit
  end

  def update
    if @user.update_attributes(user_params)
      flash[:success] = "ユーザー情報を更新しました。"
      redirect_to @user
    else
      flash[:danger] = "#{@user.name}の情報を更新できませんでした。"
      render :edit      
    end
  end

  def destroy
    @user.destroy
    flash[:success] = "#{@user.name}のデータを削除しました。"
    redirect_to users_url
  end

  def edit_basic_info
  end

  def update_basic_info
    if @user.update_attributes(basic_info_params)
      flash[:success] = "#{@user.name}の基本情報を更新しました。"
    else
      flash[:danger] = "#{@user.name}の更新は失敗しました。<br>" + @user.errors.full_messages.join("<br>")
    end
    redirect_to users_url
  end
  
  def import
    if params[:file].blank?
      flash[:danger] = "CSVファイルが選択されていません。"
    redirect_to users_url
    else
      if User.import(params[:file])
        flash[:success] = "CSVファイルのインポートに成功しました。"
      else
        flash[:danger] = "CSVファイルのインポートに失敗しました。"
      end
      redirect_to users_url
    end
  end
  
  def list_of_commuting_employees
    @users = User.all.order("id ASC")
  end

  private

    def user_params
      params.require(:user).permit(:name, :email, :affiliation, :employee_number, :uid, :password, :password_confirmation, :basic_work_time, 
                                  :designated_work_start_time, :designated_work_end_time)
    end

    def basic_info_params
      params.require(:user).permit(:name, :email, :affiliation, :employee_number, :uid, :password, :password_confirmation, :basic_work_time, 
                                  :designated_work_start_time, :designated_work_end_time)
    end
    
    def send_attendances_csv(attendances)
      bom = "\uFEFF"
      
      csv_data = CSV.generate(bom, encoding: Encoding::SJIS, row_sep: "\r\n", force_quotes: true) do |csv|
        header = %w(日付 出社時間 退社時間)
        csv << header
        
        attendances.each do |day|
          values = [
            day.worked_on.strftime("%Y年%m月%d日(#{$days_of_the_week[day.worked_on.wday]})"),
            if day.started_at.present? && (day.attendances_approval_status == "承認").present?
              l(day.started_at, format: :time)
            else
              nil
            end,
            if day.finished_at.present? && (day.attendances_approval_status == "承認").present?
              l(day.finished_at, format: :time)
            else
              nil
            end
          ]
        # csv << valueshは表の行に入る値を定義します。
          csv << values
        end
      end
      # csv出力のファイル名を定義します。
      send_data(csv_data, filename: "勤怠一覧.csv")
    end
end

app/helpers/users_helper.rb
module UsersHelper

  # 勤怠基本情報を指定のフォーマットで返します。  
  def format_basic_info(time)
    format("%.2f", ((time.hour * 60) + time.min) / 60.0)
  end
end

app/views/users/_edit_basic_info.html.erb
<% provide(:class_text, 'basic-info') %>
<% provide(:button_text, '更新') %>

<div class="modal-dialog modal-lg modal-dialog-center">
  <div class="modal-content">
    <div class="modal-header">
      <button type="button" class="close" data-dismiss="modal" aria-label="Close">
        <span aria-hidden="true">×</span>
      </button>
      <h1 class="modal-title">基本情報編集</h1>
    </div>
    <div class="modal-body">
      <div class="row">
        <div class="col-md-6 col-md-offset-3">
          <%= form_with(model: @user, url: update_basic_info_user_path(@user), local: true, method: :patch) do |f| %>
            <%= render 'shared/error_messages', object: @user %>

            <%= f.label :name, class: "label-#{yield(:class_text)}" %>
            <p><%= @user.name %></p>

            <%= f.label :department, class: "label-#{yield(:class_text)}" %>
            <%= f.text_field :department, class: "form-control" %>

            <%= f.label :basic_time, class: "label-#{yield(:class_text)}" %>
            <%= f.time_field :basic_time, class: "form-control" %>

            <%= f.label :work_time, class: "label-#{yield(:class_text)}" %>
            <%= f.time_field :work_time, class: "form-control" %>

            <div class="center">
              <%= f.submit yield(:button_text), class: "btn btn-primary btn-#{yield(:class_text)}" %>
              <button type="button" class="btn btn-default btn-<%= yield(:class_text) %>" data-dismiss="modal">
                キャンセル
              </button>
            </div>
          <% end %>
        </div>
      </div>
    </div>
  </div>
</div>

app/views/users/_form.html.erb
<%= form_with(model: @user, local: true) do |f| %>
  <%= render 'shared/error_messages', object: @user %>

  <%= f.label :name, class: "label-#{yield(:class_text)}" %>
  <%= f.text_field :name, class: "form-control" %>

  <%= f.label :email, class: "label-#{yield(:class_text)}" %>
  <%= f.email_field :email, class: "form-control" %>

  <%= f.label :department, class: "label-#{yield(:class_text)}" %>
  <%= f.text_field :department, class: "form-control" %>

  <%= f.label :password, class: "label-#{yield(:class_text)}" %>
  <%= f.password_field :password, class: "form-control" %>

  <%= f.label :password_confirmation, class: "label-#{yield(:class_text)}" %>
  <%= f.password_field :password_confirmation, class: "form-control" %>

  <%= f.submit yield(:button_text), class: "btn btn-primary btn-block btn-#{yield(:class_text)}" %>
<% end %>

app/views/users/_form_index.html.erb
<%= form_with(model: @user, url: update_basic_info_user_path(@user), local: true) do |f| %>
  <%= render 'shared/error_messages', object: @user %>
  
  <%= f.label :name, class: "label-#{yield(:class_text)}" %>
  <%= f.text_field :name, class: "form-control" %>
  
  <%= f.label :email, class: "label-#{yield(:class_text)}" %>
  <%= f.email_field :email, class: "form-control" %>
  
  <%= f.label :affiliation, class: "label-#{yield(:class_text)}" %>
  <%= f.text_field :affiliation, class: "form-control" %>
  
  <%= f.label :employee_number, class: "label-#{yield(:class_text)}" %>
  <%= f.number_field :employee_number, class: "form-control" %>
  
  <%= f.label :uid, class: "label-#{yield(:class_text)}" %>
  <%= f.text_field :uid, class: "form-control" %>
  
  <%= f.label :password, class: "label-#{yield(:class_text)}" %>
  <%= f.password_field :password, class: "form-control" %>
  
  <%= f.label :password_confirmation, class: "label-#{yield(:class_text)}" %>
  <%= f.password_field :password_confirmation, class: "form-control" %>
  
  <%= f.label :basic_work_time, class: "label-#{yield(:class_text)}" %>
  <%= f.time_field :basic_work_time, class: "form-control" %>
  
  <%= f.label :designated_work_start_time, class: "label-#{yield(:class_text)}" %>
  <%= f.time_field :designated_work_start_time, class: "form-control" %>
  
  <%= f.label :designated_work_end_time, class: "label-#{yield(:class_text)}" %>
  <%= f.time_field :designated_work_end_time, class: "form-control" %>
  
  <%= f.submit "#{yield(:btn_text)}", class: "btn btn-primary btn-block btn-#{yield(:class_text)}" %>
<% end %>

app/views/users/edit.html.erb
<% provide(:title, "基本情報の修正") %>
<% provide(:class_text, 'user--edit') %>
<% provide(:button_text, '更新') %>
<h1>基本情報の更新</h1>

<div class="row">
  <div class="col-md-6 col-md-offset-3">
    <%= render 'form', locals: {user: @user } %>
  </div>
</div>

app/views/users/edit_basic_info.js.erb
$("#edit-basic-info").html("<%= escape_javascript(render 'edit_basic_info') %>");
$("#edit-basic-info").modal("show");

app/views/users/index.html.erb
<% provide(:title, "ユーザー一覧") %>
<% provide(:btn_text, "更新") %>
<h1>ユーザー一覧</h1>

<!--あいまい検索の設定-->
<!--<div class="row">-->
<!--  <div class="col-md-offset-8">-->
<!--    <form action="/users" accept-charset="UTF-8" method="get">-->
<!--      <input name="utf8" type="hidden" value="&#x2713;" />-->
<!--      <label class="label-search" for="name">ユーザ名検索</label>-->
<!--      <div class="input-group">-->
<!--        <input type="text" name="search" id="search" value="" placeholder="キーワードを入力..." class="form-control" />-->
<!--        <span class="input-group-btn">-->
<!--          <input type="submit" value="検索" class="btn btn-primary" data-disable-with="検索" />-->
<!--        </span>-->
<!--      </div>-->
<!--    </form>-->
<!--  </div>-->
<!--</div>-->

<!--submitのボタンを配置、CSVインポートを配置-->
<%= form_with(url: import_users_path) do |f| %>
    <%= f.file_field :file, accept: '.csv' %>
    <%= f.submit "csvをインポート", class: "btn btn-primary csv-button" %>
<% end %>

<!--ページネーションの設定-->
<!--<div class="col-md-10 col-md-offset-1">-->
<!-- <%= will_paginate %><br>-->

<!--ユーザー一覧-->
<div class="col-md-11 col-md-offset-1">
<% @users.each do |user| %>
  <% unless user.admin? %>
      <table>
        <div class="row">
          <tr>
            <%= user.name %><br>
            <td class="center">
              <%= "|" %>
                <%= link_to "削除", user, method: :delete,
                    data: { confirm: "削除してよろしいですか？" }, class: "btn btn-primary" %>
            </td>
          </tr>
        </div>
      </table>
      <p>
        <div class="panel panel-default">
          <div class="panel-heding">
            <button type="button" class="btn btn-lg btn-primary" data-toggle="collapse" data-target="#collapse<%= user.id %>">編集</button>
          </div> 
            <div id="collapse<%= user.id %>" class="panel-collapse collapse out">
            <div class="panel-body">
            <%= render 'users/form_index', locals: {user: @user = User.find_by(id: user.id) } %>
          </div>
        </div>
            
        </div>
      </p>
    <% end %>
 <% end %>
<!--<%= will_paginate %>-->
</div>

<!--モーダルウインドウ表示-->
<!--<div id="edit-basic-info" class="modal fade" tabindex="-1" role="dialog" aria-hidden="true"></div>-->

app/views/users/list_of_commuting_employees.html.erb
<% provide(:title, "出勤社員一覧") %>
<h1>出勤中社員一覧</h1>

<div class="col-md-10 col-md-offset-1">
    <table class="table table-bordered table-striped" id="table-attendances">
      <thead>
        <tr>
          <th>社員番号</th>
          <th>名　　前</th>
        </tr>
      </thead>
      <tbody>
        <% @users.each do |user| %>
          <% user.attendances.where(worked_on: Date.current).each do |day| %>
            <% if day.started_at.present? && day.finished_at.blank? %>
              <tr>
                <td><%= user.employee_number %></td>
                <td><%= user.name %></td>
              </tr>
            <% end %>
          <% end %>
        <% end %>
      <tbody>
    </table>
  </div>
</div>

app/views/users/new.html.erb
<% provide(:title, 'Sign up') %>
<% provide(:class_text, 'signup') %>
<% provide(:button_text, '新規作成') %>
<h1>ユーザー登録</h1>

<div class="row">
  <div class="col-md-6 col-md-offset-3">
    <%= render 'form' %>
  </div>
</div>

app/views/users/show.html.erb
<% provide(:title, @user.name) %>
<div>
  <table class="table table-bordered table-condensed user-table" id="table-attendances">
    <tr>
      <td>
        <%= link_to "⇦", user_path(date: @first_day.prev_month), class: "btn btn-primary" %>
        <%= l(@first_day, format: :middle) %> 時間管理表  
        <%= link_to "⇨", user_path(date: @first_day.next_month), class: "btn btn-primary" %>
      </td>
      <td>
        指定勤務開始時間：<%= format_basic_info(@user.designated_work_start_time) %><br>
        指定勤務終了時間：<%= format_basic_info(@user.designated_work_end_time) %>
      </td>
      <td colspan="3">基本時間：<%= format_basic_info(@user.basic_work_time) %></td>
      <td>初日：<%= l(@first_day, format: :short) %></td>
    </tr>

    <tr>
      <td>所属：<%= @user.affiliation.present? ? @user.affiliation : "未所属" %></td>
      <td>氏名：<%= @user.name %></td>
      <td>コード</td>
      <td><%= @user.uid %></td>
      <td>出勤日数：<%= @worked_sum %>日</td>
      <td>締め：<%= l(@last_day, format: :short) %></td>
    </tr>
  </table>
</div>

<!--一般ユーザーor上長ユーザーから送られた申請を確認するボタン-->
<div class="notice">
  <% if @user.superior? && current_user?(@user) %>
    <% if @manager_sum > 0 %>
    <%= link_to "【  所属長承認申請のお知らせ 】", edit_manager_approval_notice_user_attendance_path(@user), remote: true, class: "notice-color" %>
      <span style="border: solid 3px red; color: red;"><%= link_to "#{@manager_sum}件の通知があります", edit_manager_approval_notice_user_attendance_path(@user), remote: true, class: "notice-color" %></span><br>
    <% else %>
      <%= "【  所属長承認申請のお知らせ 】" %><br>
    <% end %>
    
    <% if @attendances_sum > 0 %>
      <%= link_to "【  勤怠変更申請のお知らせ 】", edit_attendance_change_notice_user_attendance_path(@user), remote: true, class: "notice-color" %>
      <span style="border: solid 3px red; color: red;"><%= link_to "#{@attendances_sum}件の通知があります", edit_attendance_change_notice_user_attendance_path(@user), remote: true, class: "notice-color" %></span><br>
    <% else %>
      <%= "【  勤怠変更申請のお知らせ 】" %><br>
    <% end %>
    
    <% if @overtime_sum > 0 %>
      <%= link_to "【  残業申請のお知らせ 】", edit_overtime_notice_user_attendance_path(@user), remote: true, class: "notice-color" %>
      <span style="border: solid 3px red; color: red;"><%= link_to "#{@overtime_sum}件の通知があります", edit_overtime_notice_user_attendance_path(@user), remote: true, class: "notice-color" %></span>
    <% else %>
      <%= "【  残業申請のお知らせ 】" %>
    <% end %>
  <% end %>
</div>

<!--勤怠や編集や出力を行うボタン-->
<!--#にfileとrootingを入力する-->
<div class="btn-users-show">
  <br><%= link_to "勤怠を編集", attendances_edit_one_month_user_path(date: @first_day), class: "btn btn-primary" %>
  <%= link_to "CSV出力", user_path(format: :csv), class: "btn btn-primary" %>
  <%= link_to "勤怠修正ログ（承認済）", attendance_log_user_attendance_path(@user), class: "btn btn-primary" %>
</div>
<div>
  <table class="table table-bordered table-condensed table-striped table-hover" id="table-attendances">
    <thead>
      <!--rowspan:縦結合、colspan：横結合-->
      <tr>
        <th rowspan="3">残業申請</th>
        <th rowspan="3">日付</th>
        <th rowspan="3">曜日</th>
        <th rowspan="3">出社・退社登録</th>
        <th colspan="6">【実績】</th>
        <th colspan="5">所定外勤務</th>
      </tr>

      <tr>
        <th colspan="2">出社</th>
        <th colspan="2">退社</th>
        <th rowspan="2">在社時間</th>
        <th rowspan="2">備考</th>
        <th colspan="2">終了予定時間</th>
        <th rowspan="2">時間外時間</th>
        <th rowspan="2">業務処理内容</th>
        <th rowspan="2">指示者確認㊞</th>
      </tr>

      <tr>
        <th>時</th>
        <th>分</th>
        <th>時</th>
        <th>分</th>
        <th>時</th>
        <th>分</th>
      </tr>
    </thead>
  <tbody>
  <% @attendances.each do |day| %>
    <tr>
      <!--残業申請のモーダル-->
      <td><%= link_to "残業申請", edit_overtime_request_user_attendance_path(@user,day), remote: true, class: "btn btn-primary" %><br></td>
      <!--日付-->
      <td><%= l(day.worked_on, format: :short) %></td>
      <!--曜日-->
      <td class = '<%= "wday#{day.worked_on.wday}" %>'><%= $days_of_the_week[day.worked_on.wday] %></td>
      <!--出社・退社登録-->
      <td><% if btn_text = attendance_state(day) %>
            <%= link_to "#{btn_text}登録", user_attendance_path(@user, day), method: :patch, class: "btn btn-primary btn-attendance" %>
          <% end %>
      </td>
      <!--出社・退社-->
      <td><%= l(day.started_at, format: :hour) if day.started_at.present? %></td>
      <td><%= l(day.started_at, format: :min) if day.started_at.present? %></td>
      <td><%= l(day.finished_at, format: :hour) if day.finished_at.present? %></td>
      <td><%= l(day.finished_at, format: :min) if day.finished_at.present? %></td>
      <!--在社時間-->
      <td>
      <% if day.started_at.present? && day.finished_at.present? %>
        <%= str_times = working_times(day.started_at, day.finished_at, day.next_day) %>
        <% @total_working_times = @total_working_times.to_f + str_times.to_f %>
      <% end %>
      </td>
      <!--備考-->
      <td><%= day.note %></td>
      <!--終了予定時間-->
      <td><%= l(day.scheduled_end_time, format: :hour) if day.scheduled_end_time.present? %></td>
      <td><%= l(day.scheduled_end_time, format: :min) if day.scheduled_end_time.present? %></td>
      <!--時間外時間-->
      <td>
        <% if day.scheduled_end_time.present? %>                             
          <%= working_overtimes(@user.designated_work_end_time, day.scheduled_end_time, day.next_day) %>                                                    
        <% end %>
      </td>
      <!--業務処理内容-->
      <td><%= day.work_description if day.work_description.present? %></td>
      <!--指示者確認㊞-->
      <td>
        <% if day.overtime_request_status == "申請中" %>
          <%= "#{day.overtime_request_superior}へ残業#{day.overtime_request_status}" %><br>
        <% elsif (day.overtime_request_status == "承認") || (day.overtime_request_status == "否認") %>
          <%= "#{day.overtime_request_superior}より残業#{day.overtime_request_status}" %><br>
        <% end %>
        <% if day.attendances_approval_status == "申請中" %>
          <%= "#{day.attendances_request_superior}へ勤怠変更#{day.attendances_approval_status}" %><br>
        <% elsif (day.attendances_approval_status == "承認") || (day.attendances_approval_status == "否認") %>
          <%= "#{day.attendances_request_superior}より勤怠#{day.attendances_approval_status}" %><br>
        <% end %>
      </td>
    </tr>
  <% end %>
  </tbody>
    <!--フッターの記述-->
    <tfoot>
      <!--rowspan:縦結合、colspan：横結合-->
      <tr>
        <td></td>
        <td colspan="2">累計日数</td>
        <td colspan="6">総合勤務時間</td>
        <td colspan="4">累計在社時間</td>
        <td colspan="2"></td>
      </tr>
      <tr>
        <td></td>
        <td colspan="2"><%= @attendances.count %></td>
        <td colspan="6"><%= format_basic_info(@user.work_time).to_f * @worked_sum %></td>
        <td colspan="4"><%= format("%.2f", @total_working_times.to_f) %></td>
        <td colspan="2">
          <% if current_user?(@user) && (day = @user.attendances.find_by(worked_on: @first_day)) %>
            <%= form_with(model: @user, url: attendances_update_manager_approval_request_user_path(@user), local: true, method: :patch) do |f| %>
              <%= f.fields_for "attendances[]", day do |attendance| %>
                <%= "所属長承認: " %>
                  <% if day.manager_approval_status.nil? && day.manager_request_status.nil? %>
                    <%= "未" %><br>
                  <% elsif day.manager_request_status == "申請中" %>
                    <%= "#{day.manager_request_superior}へ#{day.manager_request_status}" %><br>
                  <% elsif (day.manager_approval_status == "承認") || (day.manager_approval_status == "否認") %>
                    <%= "#{day.manager_request_superior}より#{day.manager_approval_status}済" %><br>
                  <% end %>
                  <!--:name, :nameに変更-->
                    <%= attendance.collection_select :manager_request_superior, @superiors, :name, :name, { include_blank: true }, required: true %>
              <% end %>
                  <%= f.submit "申請", class: "btn btn-primary" %>
            <% end %>
          <% end %>
        </td>
      </tr>
    </tfoot>   
  </table>
</div>

<!--モーダルウインドウ表示-->
<div id="edit-overtime-request" class="modal fade" tabindex="-1" role="dialog" aria-hidden="true"></div>
<div id="edit-overtime-notice" class="modal fade" tabindex="-1" role="dialog" aria-hidden="true"></div>
<div id="edit-attendance-change-notice" class="modal fade" tabindex="-1" role="dialog" aria-hidden="true"></div>
<div id="edit-manager-approval-notice" class="modal fade" tabindex="-1" role="dialog" aria-hidden="true"></div>