config/routes.rb
Rails.application.routes.draw do
  root 'static_pages#top'
  get '/signup', to: 'users#new'

  # ログイン機能
  get    '/login', to: 'sessions#new'
  post   '/login', to: 'sessions#create'
  delete '/logout', to: 'sessions#destroy'
  
  # 拠点情報
  resources :bases
  
  resources :users do
    collection { post :import }
    member do
      get 'edit_basic_info'
      patch 'update_basic_info'
      # 1ヶ月の変更申請
      get 'attendances/edit_one_month'
      patch 'attendances/update_one_month' # この行が追加対象です。
      # 1ヶ月の勤怠申請
      patch 'attendances/update_manager_approval_request'
      # 勤怠の確認
      get 'show_confirmation'
      # 出勤社員一覧
      get 'list_of_commuting_employees'
    end
    
    resources :attendances, only: :update do
      member do
        # 残業申請
        get 'edit_overtime_request'
        patch 'update_overtime_request'
        # 残業承認
        get 'edit_overtime_notice'
        patch 'update_overtime_notice'
        # 勤怠承認
        get 'edit_attendance_change_notice'
        patch 'update_attendance_change_notice'
        # 所属長承認
        get 'edit_manager_approval_notice'
        patch 'update_manager_approval_notice'
        # 勤怠修正ログ
        get 'attendance_log'
      end
    end
  end
end

app/models/attendance.rb
class Attendance < ApplicationRecord
  belongs_to :user
  
  # 日付が必ず存在させるために検証を追加
  validates :worked_on, presence: true
  # 備考欄は最大の長さ50文字までの検証を追加
  validates :note, length: { maximum: 50 }

  # 出勤時間が存在しない場合、退勤時間は無効
  validate :finished_at_is_invalid_without_a_started_at
  # 退勤時間が存在しない場合、出勤時間は無効。
  validate :started_at_is_invalid_without_a_finished_at, on: :update_one_month
  # 出勤・退勤時間どちらも存在する時、翌日チェックがない時、出勤時間より早い退勤時間は無効
  validate :started_at_than_finished_at_fast_if_invalid

  def finished_at_is_invalid_without_a_started_at
    errors.add(:started_at, "が必要です") if started_at.blank? && finished_at.present?
  end
  
  def started_at_is_invalid_without_a_finished_at
    errors.add(:finished_at, "が必要です") if finished_at.blank? && started_at.present?
  end

  def started_at_than_finished_at_fast_if_invalid
    if started_at.present? && finished_at.present? && !next_day.present?
      errors.add(:started_at, "より早い退勤時間は無効です") if started_at > finished_at
    end
  end
end

app/controllers/attendances_controller.rb
class AttendancesController < ApplicationController
  before_action :set_user, only: [:edit_one_month, :update_one_month, :update_manager_approval_request]
  before_action :set_user_id, only: [:update, :edit_overtime_request, :update_overtime_request, :edit_overtime_notice, :update_overtime_notice, 
                                    :edit_attendance_change_notice, :update_attendance_change_notice, :edit_manager_approval_notice, :update_manager_approval_notice, :attendance_log]
  before_action :set_attendance, only: [:update, :edit_overtime_request, :update_overtime_request]
  before_action :set_superior, only: [:edit_one_month, :edit_overtime_request]
  before_action :logged_in_user, only: [:update, :edit_one_month, :edit_overtime_request, :update_overtime_request, :edit_attendance_change_notice, :update_attendance_change_notice]
  before_action :correct_user, only: [:edit_one_month, :edit_overtime_request, :update_overtime_request, :edit_overtime_notice, :edit_attendance_change_notice]
  before_action :admin_or_correct_user, only: [:update, :edit_one_month, :update_one_month]
  before_action :set_one_month, only: [:edit_one_month, :update_one_month, :edit_overtime_request, :attendance_log]
  before_action :not_admin, only: [:edit_one_month]

  UPDATE_ERROR_MSG = "勤怠登録に失敗しました。やり直してください。"

  def update
    # 出勤時間が未登録であることを判定します。
    if @attendance.started_at.nil?
      if @attendance.update_attributes(started_at: Time.current)
        flash[:info] = "おはようございます！"
      else
        flash[:danger] = UPDATE_ERROR_MSG
      end
    elsif @attendance.finished_at.nil?
      if @attendance.update_attributes(finished_at: Time.current)
        flash[:info] = "お疲れ様でした。"
      else
        flash[:danger] = UPDATE_ERROR_MSG
      end
    end
    redirect_to @user
  end

  # 勤怠変更申請
  def edit_one_month
  end

  # 勤怠変更承認
  def update_one_month
    a_count = 0
    ActiveRecord::Base.transaction do # トランザクションを開始します。
      attendances_params.each do |id, item|
        if item[:attendances_request_superior].present?
          if item[:edit_started_at].blank? && item[:edit_finished_at].present?
            flash[:danger] = "出勤時間が必要です。"
            redirect_to attendances_edit_one_month_user_url(date: params[:date])
            return
          elsif item[:edit_started_at].present? && item[:edit_finished_at].blank?
            flash[:danger] = "退勤時間が必要です。"
            redirect_to attendances_edit_one_month_user_url(date: params[:date])
            return
          elsif item[:edit_started_at].present? && item[:edit_finished_at].present? && item[:edit_started_at].to_s > item[:edit_finished_at].to_s && item[:next_day] == "0"
            flash[:danger] = "時刻に誤りがあります。"
            redirect_to attendances_edit_one_month_user_url(date: params[:date])
            return
          end
          attendance = Attendance.find(id)
          attendance.attendances_approval_status = "申請中"
          a_count += 1
          attendance.update!(item)
        end
      end
      if a_count > 0
        flash[:success] = "勤怠編集を#{a_count}件、申請しました。"
        redirect_to user_url(date: params[:date])
        return
      else
        flash[:danger] = "上長を選択してください。"
        redirect_to attendances_edit_one_month_user_url(date: params[:date])
        return
      end
    end
  rescue ActiveRecord::RecordInvalid # トランザクションによるエラーの分岐です。
    flash[:danger] = "無効な入力データがあった為、更新をキャンセルしました。"
    redirect_to attendances_edit_one_month_user_url(date: params[:date])
    return
  end

  # 残業申請のモーダル表示
  def edit_overtime_request
  end

  # 残業申請のモーダル更新
  def update_overtime_request
    if overtime_request_params[:scheduled_end_time].blank? || overtime_request_params[:work_description].blank? || overtime_request_params[:overtime_request_superior].blank?
      flash[:danger] = "終了予定時間、業務処理内容、または、指示者確認印がありません"
    else
    if overtime_request_params[:scheduled_end_time].present? && overtime_request_params[:work_description].present? && overtime_request_params[:overtime_request_superior].present?
      params[:attendance][:overtime_request_status] = "申請中"
      @attendance.update(overtime_request_params)
      flash[:success] = "残業申請をしました"
    else
      flash[:danger] = "残業申請が正しくありません"
    end
    end
    redirect_to @user
  end
  
  # 残業申請のお知らせモーダルの表示
  def edit_overtime_notice
    # @user.id→@user.nameに変更
    @attendances = Attendance.where(overtime_request_superior: @user.name, overtime_request_status: "申請中").order(:worked_on).group_by(&:user_id)
  end
  
  # 残業申請のお知らせモーダル更新
  def update_overtime_notice
    overtime_notice_params.each do |id, item|
      attendance = Attendance.find(id)
      if item[:overtime_check] == "1"
        if item[:overtime_request_status] == "なし"
          attendance.scheduled_end_time = nil
          attendance.overtime_next_day = nil
          attendance.work_description = nil
          attendance.overtime_request_superior = nil
        end
        attendance.update(item)
        flash[:success] = "残業申請を承認しました。"
      else
        flash[:danger] = "残業申請の承認に失敗しました。" 
      end
    end
    redirect_to user_url(@user)
  end
  
  # 勤怠変更申請のお知らせモーダルの表示
  # @user.id→@user.nameに変更
  def edit_attendance_change_notice
    @attendances = Attendance.where(attendances_request_superior: @user.name, attendances_approval_status: "申請中").order(:worked_on).group_by(&:user_id)
  end
  
  # 勤怠変更申請のモーダルの更新
  def update_attendance_change_notice
    a_count = 0
    attendance_change_notice_params.each do |id, item|
    attendance = Attendance.find(id)
      if item[:attendances_approval_check] == "1"
        if item[:attendances_approval_status] == "申請中" || item[:attendances_approval_status] == "承認"
          attendance.begin_started = attendance.started_at
          attendance.begin_finished = attendance.finished_at
          item[:started_at] = attendance.edit_started_at
          item[:finished_at] = attendance.edit_finished_at
        end
        a_count += 1
        attendance.update(item)
      end
      attendance.update(edit_started_at: nil, edit_finished_at: nil, note: nil, attendances_approval_status: nil, next_day: nil) if item[:attendances_approval_status] == "なし"
  end
  if a_count > 0
    flash[:success] = "勤怠変更の承認に成功しました。"
  else
    flash[:danger] = "勤怠変更の承認に失敗しました。"
  end
    redirect_to user_url(@user)
  end
  
  # 1ヶ月分の勤怠申請 
  def update_manager_approval_request
    manager_approval_request_params.each do |id, item|
      attendance = Attendance.find(id)
      if item[:manager_request_superior].present?
        item[:manager_request_status] = "申請中"
        if attendance.update(item)
          flash[:success] = "#{attendance.manager_request_superior}へ1ヶ月の勤怠を申請しました。"
        else
          flash[:danger] = "1ヶ月の勤怠変更に失敗しました。"
        end
      else
        flash[:danger] = "所属長を選択してください。"
      end
    end
    redirect_to user_url(date: params[:date])
  end
  
  # 所属長承認お知らせモーダルの表示
  # @user.id→@user.nameに変更
  def edit_manager_approval_notice
    @attendances = Attendance.where(manager_request_superior: @user.name, manager_request_status: "申請中").order(:worked_on).group_by(&:user_id)
  end
  
  # 所属長承認お知らせモーダルの表示
  def update_manager_approval_notice
    manager_approval_notice_params.each do |id, item|
    attendance = Attendance.find(id)
    if item[:manager_approval_check] == "1"
      if ["承認", "否認"].include? item[:manager_approval_status]
        attendance.manager_request_status = nil
      end
      attendance.update(item)
      flash[:success] = "所属長承認申請の結果を送信しました。"
    else
      flash[:danger] = "承認確認のチェックを入れてください。"
    end
    end
    redirect_to user_url(@user)
  end
  
  # 勤怠修正ログ
  def attendance_log
    if Attendance.where(manager_approval_status: "承認").order(:worked_on).group_by(&:user_id)
      if params["select_year(1i)"].nil?
        @first_day = Date.current.beginning_of_month
      else
        @first_day = Date.parse("#{params["select_year(1i)"]}/#{params["select_month(2i)"]}/1")
      end
      last_day = @first_day.end_of_month
      @attendances = @user.attendances.where(worked_on: @first_day..last_day, attendances_approval_status: "承認").order(:worked_on)
    end
  end
  
  private

    # 1ヶ月分の勤怠情報を扱います。
    def attendances_params
      params.require(:user).permit(attendances: [:started_at, :finished_at, :edit_started_at, :edit_finished_at, :note, :next_day, :attendances_request_superior, :attendances_approval_status])[:attendances]
    end
    #残業申請のモーダルの情報を扱います。
    def overtime_request_params
      params.require(:attendance).permit(:scheduled_end_time, :work_description, :overtime_next_day, :overtime_request_superior, :overtime_request_status)
    end
    
    # 残業申請承認
    def overtime_notice_params
      params.require(:user).permit(attendances: [:overtime_request_status, :overtime_check])[:attendances]
    end
    
    # 勤怠変更申請承認
    def attendance_change_notice_params
      params.require(:user).permit(attendances: [:attendances_approval_status, :attendances_approval_check])[:attendances]
    end
    
    # 1ヶ月の勤怠変更申請
    def manager_approval_request_params
      params.require(:user).permit(attendances: [:manager_request_superior, :manager_request_status])[:attendances]
    end
    
    # 所属長申請
    def manager_request_params
      params.require(:user).permit(attendances: [:manager_request_superior, :manager_request_status])[:attendances]
    end

    # 所属長承認
    def manager_approval_notice_params
      params.require(:user).permit(attendances: [:manager_approval_status, :manager_approval_check])[:attendances]
    end
end

app/helpers/attendances_helper.rb
module AttendancesHelper

  def attendance_state(attendance)
    # 受け取ったAttendanceオブジェクトが当日と一致するか評価します。
    if Date.current == attendance.worked_on
      return '出社' if attendance.started_at.nil?
      return '退社' if attendance.started_at.present? && attendance.finished_at.nil?
    end
    # どれにも当てはまらなかった場合はfalseを返します。
    return false
  end

  # 出勤時間と退勤時間を受け取り、在社時間を計算して返します。
  def working_times(start, finish, next_day)
    if next_day && (start >= finish)
      format("%.2f", (((finish - start) / 60) / 60.0) + 24)
    else
      format("%.2f", (((finish - start) /60) / 60.0))
    end
  end
  
  # 時間外計算を計算して返します。
  def working_overtimes(designated_work_end_time, scheduled_end_time, next_day)
    if next_day
      format("%.2f", ((scheduled_end_time.hour - designated_work_end_time.hour) + (scheduled_end_time.min - designated_work_end_time.min) / 60.0) +24)
    else 
      format("%.2f", (scheduled_end_time.hour - designated_work_end_time.hour) + (scheduled_end_time.min - designated_work_end_time.min) / 60.0)
    end
  end
  
  #残業申請のステータス
    def overtime_status_text(status)
      case status
      when "申請中"
        "申請中"
      when "否認"
        "残業否認済"
      when "承認"
        "残業承認済"
      when "なし"
        "残業なし"
      else
      end
    end
end

app/views/attendances/_edit_attendance_change_notice.html.erb
<% provide(:btn_text, '変更を返信する') %> 

<div class="modal-dialog modal-lg modal-dialog-center">
  <div class="modal-content">
    <div class="modal-header">
      <button type="button" class="close" data-dismiss="modal" aria-label="Close">
        <span aria-hidden="true">×</span>
      </button>
    </div>
    <div class="modal-body">
      <div class="row">
        <div class="col-md-12">
          <%= form_with(model: @user, url: update_attendance_change_notice_user_attendance_path(@user), local: true, method: :patch) do |f| %>
            <% @attendances.each do |id, attendances| %>
              <% user = User.find(id) %>
              <!--user.id→user.nameに変更-->
              <h1 class="modal-title"><%= "【#{user.name}からの勤怠変更申請】" %></h1>
              <table class="table table-bordered table-condensed table-hover" id="table-attendances">
                <thead>
                  <tr>
                    <th rowspan="3">日付</th>
                    <th rowspan="3">曜日</th>
                    <th colspan="4">変更前</th>
                    <th colspan="4">変更後</th>
                    <th rowspan="3">備考</th>
                    <th rowspan="3">指示者確認㊞</th>
                    <th rowspan="3">変更</th>
                    <th rowspan="3">勤怠を確認する</th>
                  </tr>
                  <tr>
                    <th colspan="2">出社</th>
                    <th colspan="2">退社</th>
                    <th colspan="2">出社</th>
                    <th colspan="2">退社</th>
                  </tr>
                  <tr>
                    <th>時</th>
                    <th>分</th>
                    <th>時</th>
                    <th>分</th>
                    <th>時</th>
                    <th>分</th>
                    <th>時</th>
                    <th>分</th>
                  </tr>
                </thead>
                <tbody>
                  <% attendances.each do |day| %>              
                    <%= f.fields_for "attendances[]", day do |attendance| %>  
                      <tr>
                        <td><%= l(day.worked_on, format: :short) %></td>
                        <td class="<%= "wday#{day.worked_on.wday}" %>"><%= $days_of_the_week[day.worked_on.wday] %></td>
                        <!--変更前・出勤-->
                        <td><%= day.started_at.try(:strftime, "%H") %></td>
                        <td><%= day.started_at.try(:strftime, "%M") %></td>
                        <!--変更前・退勤-->
                        <td><%= day.finished_at.try(:strftime, "%H") %></td>
                        <td><%= day.finished_at.try(:strftime, "%M") %></td>
                        <!--変更後・出社-->
                        <td><%= day.edit_started_at.try(:strftime, "%H") %></td>
                        <td><%= day.edit_started_at.try(:strftime, "%M") %></td>
                        <!--変更後・退社-->
                        <td><%= day.edit_finished_at.try(:strftime, "%H") %></td>
                        <td><%= day.edit_finished_at.try(:strftime, "%M") %></td>
                        <td><%= day.note %></td>
                        <td><%= attendance.select :attendances_approval_status, ['', 'なし', '申請中', '承認', '否認'] %></td>
                        <td><%= attendance.check_box :attendances_approval_check %></td>
                        <td><%= link_to "確認", show_confirmation_user_path(id, date: day.worked_on.beginning_of_month), target: :_blank, rel: "noopener noreferrer", class: "btn btn-sm btn-primary" %></td>
                      </tr>
                    <% end %>
                  <% end %>
                </tbody>
              </table>
              <div class="center">
                <%= f.submit yield(:btn_text), class: "btn btn-primary btn-block" %>
              </div>
            <% end %>
          <% end %>
        </div>
      </div>
    </div>
  </div>
</div>

app/views/attendances/_edit_manager_approval_notice.html.erb
<% provide(:btn_text, '変更を返信する') %>

<div class="modal-dialog modal-lg modal-dialog-center">
  <div class="modal-content">
    <div class="modal-header">
      <button type="button" class="close" data-dismiss="modal" aria-label="Close">
        <span aria-hidden="true">×</span>
      </button>
    </div>
    <div class="modal-body">
      <div class="row">
        <div class="col-md-12">
          <%= form_with(model: @user, url: update_manager_approval_notice_user_attendance_path(@user), local: true, method: :patch) do |f| %>
            <% @attendances.each do |id, attendances| %>
              <% user = User.find(id) %>
              <!--user.id→user.nameに変更-->
              <h1 class="modal-title"><%= "【#{user.name}から1ヶ月の勤怠申請】" %></h1>
              <table class="table table-bordered table-condensed table-hover" id="table-attendances">
                <thead>
                  <tr>
                    <th>月</th>
                    <th>指示者確認㊞</th>
                    <th>変更</th>
                    <th>勤怠を確認する</th>
                  </tr>
                </thead>
                <tbody>
                  <% attendances.each do |day| %>
                    <%= f.fields_for "attendances[]", day do |attendance| %>
                      <tr>
                        <!--月-->
                        <td><%= day.worked_on.month %>月</td>
                        <!--指示者確認㊞-->
                        <td><%= attendance.select :manager_approval_status, ['', 'なし', '申請中', '承認', '否認'] %></td>
                        <!--変更-->
                        <td><%= attendance.check_box :manager_approval_check %></td>
                        <!--勤怠を確認する-->
                        <td><%= link_to "確認", show_confirmation_user_path(id, date: day.worked_on.beginning_of_month), target: :_blank, rel: "noopener noreferrer", class: "btn btn-sm btn-primary" %></td>
                      </tr>
                    <% end %>
                  <% end %>
                </tbody>
              </table>
              <div class="center">
                <%= f.submit yield(:btn_text), class: "btn btn-primary btn-block" %>
              </div>
            <% end %>
          <% end %>
        </div>
      </div>
    </div>
  </div>
</div>

app/views/attendances/_edit_overtime_notice.html.erb
<% provide(:btn_text, '変更を送信する') %>

<div class="modal-dialog modal-lg modal-dialog-center">
  <div class="modal-content">
    <div class="modal-header">
      <button type="button" class="close" data-dismiss="modal" aria-label="Close">
        <span aria-hidden="true">×</span>
      </button>
    </div>
    <div class="modal-body">
      <div class="row">
        <div class="col-md-12">
          <%= form_with(model: @user, url: update_overtime_notice_user_attendance_path(@user), local: true, method: :patch) do |f| %>
            <% @attendances.each do |id, attendances| %>
              <% user = User.find(id) %>
              <!--user.id→user.nameに変更-->
              <h1 class="modal-title"><%= "【#{user.name}からの残業申請】" %></h1>
              <table class="table table-bordered table-condensed table-hover" id="table-attendances">
                <thead>
                  <tr>
                    <th rowspan="2">日付</th>
                    <th rowspan="2">曜日</th>
                    <th colspan="2">終了予定時間</th>
                    <th colspan="2">指定勤務終了時間</th>
                    <th rowspan="2">時間外時間</th>
                    <th rowspan="2">業務処理内容</th>
                    <th rowspan="2">指示者確認㊞</th>
                    <th rowspan="2">変更</th>
                    <th rowspan="2">勤怠を確認する</th>
                  </tr>
                  <tr>
                    <th>時</th>
                    <th>分</th>
                    <th>時</th>
                    <th>分</th>
                  </tr>
                </thead>
                <tbody>
                  <% attendances.each do |day| %>              
                    <%= f.fields_for "attendances[]", day do |attendance| %>  
                      <tr>
                        <td><%= l(day.worked_on, format: :short) %></td>
                        <td class="<%= "wday#{day.worked_on.wday}" %>"><%= $days_of_the_week[day.worked_on.wday] %></td>
                        <td><%= day.scheduled_end_time.try(:strftime,"%H") %></td>
                        <td><%= day.scheduled_end_time.try(:strftime,"%M") %></td>
                        <td><%= l(user.designated_work_end_time, format: :hour) %></td>
                        <td><%= l(user.designated_work_end_time, format: :min) %></td>
                        <td><%= working_overtimes(day.scheduled_end_time, user.designated_work_end_time, day.overtime_next_day) if day.scheduled_end_time.present? %></td>
                        <td><%= day.work_description %></td> 
                        <td><%= attendance.select :overtime_request_status, ['', 'なし', '申請中', '承認', '否認'] %></td>
                        <td><%= attendance.check_box :overtime_check %></td>
                        <td><%= link_to "確認", show_confirmation_user_path(id, date: day.worked_on.beginning_of_month), target: :_blank, rel: "noopener noreferrer", class: "btn btn-sm btn-primary" %></td>
                      </tr>
                    <% end %>
                  <% end %>
                </tbody>
              </table>
              <div class="center">
                <%= f.submit yield(:btn_text), class: "btn btn-primary btn-block" %>
              </div>
            <% end %>
          <% end %>
        </div>
      </div>
    </div>
  </div>
</div>

app/views/attendances/_edit_overtime_request.html.erb
<% provide(:class_text, 'overtime-request') %>
<!--返信→送信に変更-->
<% provide(:btn_text, '変更を送信する') %>

<div class="modal-dialog modal-lg modal-dialog-center">
  <div class="modal-content">
    <div class="modal-header">
      <button type="button" class="close" data-dismiss="modal" aria-label="Close">
        <span aria-hidden="true">×</span>
      </button>
      <div class="modal-title">【残業申請】</div>
    </div>
    <div class="modal-body">
      <div class="row">
        <div class="col-md-12">
          <%= form_with(model: @attendance, url: update_overtime_request_user_attendance_path(@user, @attendance), local: true, method: :patch) do |f| %>
          <table class="table table-bordered table-condensed table-hover" id="table-attendances">
                <thead>
                  <tr>
                    <th>日付</th>
                    <th>曜日</th>
                    <th>終了予定時間</th>
                    <th>翌日</th>
                    <th>業務処理内容</th>
                    <th>指示者確認㊞</th>
                  </tr>
                </thead>
                <tbody>
                  <tr>
                    <td><%= l(@attendance.worked_on, format: :short) %></td>
                    <td><%= $days_of_the_week[@attendance.worked_on.wday] %></td>
                    <td><%= f.time_field :scheduled_end_time, class: 'form-control' %></td>
                    <td><%= f.check_box :overtime_next_day, id: "next_day" %></td>
                    <td><%= f.text_field :work_description, class: 'form-control' %></td>
                    <!--:name, :nameだと名前が出力される-->
                    <!--:id, :nameであればuserのidが表示される。-->
                    <!--:name, :nameに変更-->
                    <td><%= f.collection_select( :overtime_request_superior, @superiors, :name, :name, {prompt: ""}) %></td>
                  </tr>
                </tbody>
              </table>
              <div class="center">
                <%= f.submit yield(:btn_text), class: "btn btn-primary btn-block" %>
              </div>
          <% end %>
        </div>
      </div>
    </div>
  </div>
</div>

app/views/attendances/attendance_log.html.erb
<% provide(:title, "勤怠ログ") %>

<div class="container">
    <h1>勤怠修正ログ</h1>
        <%= form_with(url: attendance_log_user_attendance_path, local: true, method: :get) do |f| %>
            <div class="pull-left">
              <tr>
                <td><%= f.date_select :select_year, {discard_month: "true", selected: @first_day}, class: "search-date"%></td>
              </tr>
              <tr>
                <td><%= f.date_select :select_month, {discard_year: "true", discard_day: "true", selected: @first_day}, class: "search-date"%></td>
              </tr>
              <br><%= f.submit "検索", class: "btn btn-md btn-primary"%>
            </div>
        <% end %>
        
        <table class="table table-bordered table-condensed table-hover" id="table-attendances">
            <thead>
              <tr>
                <th>日付</th>
                <th>変更前出社時間</th>
                <th>変更前退社時間</th>
                <th>変更後出社時間</th>
                <th>変更後退社時間</th>
                <th>指示者</th>
                <th>承認日</th>
              </tr>
            </thead>
            <tbody>
                <% @attendances.each do |day| %>
                  <tr>
                    <td><%= l(day.worked_on, format: :short) %></td>
                    <td><%= day.begin_started.strftime("%R") if day.begin_started.present? %></td>
                    <td><%= day.begin_finished.strftime("%R") if day.begin_finished.present? %></td>
                    <td><%= day.started_at.strftime("%R") if day.started_at.present? %></td>
                    <td><%= day.finished_at.strftime("%R") if day.finished_at.present? %></td>
                    <td><%= day.attendances_request_superior %></td>
                    <td><%= l(day.updated_at, format: :long) %></td>
                  </tr>
                <% end %>
            </tbody>
        </table>
</div>

app/views/attendances/edit_attendance_change_notice.js.erb
$("#edit-attendance-change-notice").html("<%= escape_javascript(render 'edit_attendance_change_notice') %>");
$("#edit-attendance-change-notice").modal("show");

app/views/attendances/edit_manager_approval_notice.js.erb
$("#edit-manager-approval-notice").html("<%= escape_javascript(render 'edit_manager_approval_notice') %>");
$("#edit-manager-approval-notice").modal("show");

app/views/attendances/edit_one_month.html.erb
<% provide(:title, @user.name) %>
<%= form_with(model: @user, url: attendances_update_one_month_user_path(date: @first_day), local: true, method: :patch) do |f| %>
  <div>
    <h1>勤怠変更申請</h1>
    <table class="table table-bordered table-condensed table-hover" id="table-attendances">
      <thead>
        <tr>
          <th>日付</th>
          <th>曜日</th>
          <th>出社</th>
          <th>退社</th>
          <th>翌日</th>
          <th>在社時間</th>
          <th>備考</th>
          <th>指示者確認㊞</th>
        </tr>
      </thead>
      <tbody>
        <% @attendances.each do |day| %>
          <%= f.fields_for "attendances[]", day do |attendance| %>
          <tr>
            <td><%= l(day.worked_on, format: :short) %></td>
            <td class="<%= "wday#{day.worked_on.wday}" %>"><%= $days_of_the_week[day.worked_on.wday] %></td>
            <% if (Date.current < day.worked_on) %>
              <td><%= attendance.time_field :edit_started_at, readonly: true, class: "form-control" %></td>
              <td><%= attendance.time_field :edit_finished_at, readonly: true, class: "form-control" %></td>
            <% else %>
              <td><%= attendance.time_field :edit_started_at, class: "form-control" %></td>
              <td><%= attendance.time_field :edit_finished_at, class: "form-control" %></td>
            <% end %>
              <td><%= attendance.check_box :next_day, id: "next_day" %></td>
              <td>
              <% if day.started_at.present? && day.finished_at.present? %>
              <%= working_times(day.started_at, day.finished_at, day.next_day) %>
              <% end %>
              </td>
              <td><%= attendance.text_field :note, class: "form-control" %></td>
              <!--:id, :name→:name, :name,に変更-->
              <td><%= attendance.collection_select( :attendances_request_superior, @superiors, :name, :name, {prompt: ""}) %></td>
          </tr>
          <% end %>
        <% end %>
      </tbody>
      </table>
  </div>

  <div class="center">
    <%= link_to "キャンセル", user_path(date: @first_day), class: "btn btn-lg btn-default" %>
    <%= f.submit "編集を保存する", class: "btn btn-lg btn-primary" %>
  </div>
<% end %>

app/views/attendances/edit_overtime_notice.ja.erb
$("#edit-overtime-notice").html("<%= escape_javascript(render 'edit_overtime_notice') %>");
$("#edit-overtime-notice").modal("show");

app/views/attendances/edit_overtime_request.js.erb
$("#edit-overtime-request").html("<%= escape_javascript(render 'edit_overtime_request') %>");
$("#edit-overtime-request").modal("show");